version: "2.0"
services:
  portal:
    image: nginx:alpine
    container_name:
        "nginx"
    volumes:
      - C:/Users/RameshRajendran/stash/github/spring-mvc-example/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - tomcatOne:spring1
      - tomcatTwo:spring2
  tomcatOne:
    image: spring-mvc-example
    container_name:
        "tomcatOne"
    links:
      - redis:redis
  tomcatTwo:
    image: spring-mvc-example
    container_name:
        "tomcatTwo"
    links:
      - redis:redis
  redis:
    image: redis:alpine
    container_name:
      "redis"
    ports:
      - "6379"
