version: '2.0'
services:
    elasticsearch:
      image: elasticsearch
      ports:
        - "9200:9200"
    logstash:
      image: logstash:alpine
      volumes:
        - C:/Users/RameshRajendran/stash/github/spring-mvc-example/elk/logstash.conf:d
      links:
        - elasticsearch
    kibana:
      image: kibana
      ports:
          - "5601:5601"