version: '2.0'
services:
  portal:
    image: nginx:alpine
    container_name: redis
    volumes:
      - C:/Users/RameshRajendran/stash/github/spring-mvc-example/redis/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - db1:redis-db1
      - db2:redis-db2
  db1:
    image: redis:alpine
    ports:
      - "6743"
    volumes:
      - c:/tmp/data:/data:rw
  db2:
    image: redis:alpine
    ports:
      - "6743"
    volumes:
      - c:/tmp/data:/data:rw